### ISSUE TITLE
Dates not properly formatted on pop-up

### ISSUE THREAD

**Issue by karmstro77** [Esri/live-work-locate#101]
![date_format](https://cloud.githubusercontent.com/assets/6819070/4652365/83d5a0b8-54a4-11e4-85b5-40ade5448930.png)

**Comment by lindsayking** [comment]
This popup should be consuming the date format from the webmap popup.

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will provide this fix in next release.

**Comment by LindsayThomas** [comment]
Dates from popups are honored. Tested on Server and AGOL Feature Server
