### ISSUE TITLE
Order of query results not consistent

### ISSUE THREAD

**Issue by karmstro77** [Esri/live-work-locate#102]
I have built a configuration of the Live,Work,Locate app to work with crime data. 
http://charlotte93.esri.com/Kevin/CrimeViewer/default.htm#?app=CRIME
I would like the results of the query to match the order of the layers in my config file but the results seem to return in random order. To reproduce, open app and use default address search for 5 min drive time. Results are returned. Notice the order of the crime types. Then change drive time to 10 or 15min. The results are reordered. 

Service Layer Order
![map_layers](https://cloud.githubusercontent.com/assets/6819070/4865756/48e24c8e-6126-11e4-94b5-d608323bc02b.png)

App Layer Order
![app_layers](https://cloud.githubusercontent.com/assets/6819070/4865758/4f7d0aca-6126-11e4-85d4-c7eda0a554ee.png)

**Comment by lindsayking** [comment]
@CTLocalGovTeam  The What's nearby panel should reflect the order of the layers in the SearchSettings in the configuration file.

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will provide this fix in next release.

**Comment by LindsayThomas** [comment]
@NikkiGolding We cannot verify this issue until #128 is resolved. Because the duplicates are being added into the search results we cannot determine if the order is correct.

**Comment by LindsayThomas** [comment]
SG (Work is good, Locate missing seaports \ high school attainment,
