### ISSUE TITLE
Popup Header only shows 20 characters. Then you get a ... however there is lots of space left

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/live-work-locate#114]
Popup Header only shows 20 characters. Then you get a ... however there is lots of space left

similar to 
https://github.com/Esri/site-selector/issues/119

**Comment by lindsayking** [comment]
@CTLocalGovTeam  Please follow the approach being used for https://github.com/Esri/site-selector/issues/119.

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will provide this fix in next release.

**Comment by LindsayThomas** [comment]
LT - Verified on Local Gov Config (Park and Recreation areas no longer has the ...)

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam This is not the same fix as we are seeing in the Site Selector. Please follow the same approach as provided in Esri/site-selector#119.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas In Live Work Locate we had defined the limit for the Info popup heading where as in Site Selector we had’nt. We have resolved this issue to address it like Site Selector and shall deliver it in the next release. Please find the mockup for your reference.

![popup1](https://cloud.githubusercontent.com/assets/2959186/6846149/d51aa9de-d3e1-11e4-85ea-98b24b819502.png)
![popup2](https://cloud.githubusercontent.com/assets/2959186/6846150/d52187d6-d3e1-11e4-8133-8c0dba94be87.png)

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam I just wanted to confirm what we are seeing in the images. 
The first image in the header is illustrating the length of the string will now use all the space. 
The second image in the header is illustrating the length of the string will now use all the space when the next and previous button exist.

(Because the images are using testing data we wanted to verify this is what we are seeing)
