### ISSUE TITLE
Better Support for Linear Features in the webmap

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/live-work-locate#115]
When a linear feature is in the webmap and has a popup enabled. Sometimes when you click on it. You will be pushed into a blank screen with just the outline of the popup window. 

Other times, clicking on a liner feature that is close in proximity to a point feature will display the popup at the top of the linear feature. The popup allows you to tab through the point and line feature but the point feature is about 20 KM away on the map.

**Comment by lindsayking** [comment]
@CTLocalGovTeam  The popup should display where the mouse click occurs.

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will provide this fix in next release.

**Comment by LindsayThomas** [comment]
Verified
