### ISSUE TITLE
Update app to use layer name from the service and use the webmap layer name as well

### ISSUE THREAD

**Issue by lindsayking** [Esri/live-work-locate#118]

**Comment by lindsayking** [comment]
Fixed in @jmhauck commit https://github.com/Esri/live-work-locate/commit/9b7cb3f7ccbbd171631be3492b7a3e16b360b8b8, part of pull request #116.

**Comment by lindsayking** [comment]
Updated the issue:  The app needs to be updated to use only the layer name from the webmap.  We want to remove any dependency on the layer id and remove the QueryLayerId from the config.js.

**Comment by lindsayking** [comment]
UPDATE:  We have revised the approach we want to take with this.  We want to use a combination of the layer name and the layerID. The layer name needs to be read from the webmap. The index number should come from the service (e.g. the "0" at the end of http://50.18.115.76:6080/arcgis/rest/services/WaterAccess/MapServer/0).

**Comment by LindsayThomas** [comment]
updated title

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will provide this fix in next release.

**Comment by NikkiGolding** [comment]
We cannot verify this issue until #128 is resolved. Because the duplicates are being added into the search results we cannot determine if the issue has been resolved.

**Comment by LindsayThomas** [comment]
Test fully. same ID's different Services

**Comment by lindsayking** [comment]
@NikkiGolding   Tested state gov implementation using multiple layers with the same ID but coming from different services: all layers show up in the search results.
