### ISSUE TITLE
Update config.js text in search settings to clarify layer name and id source

### ISSUE THREAD

**Issue by lindsayking** [Esri/live-work-locate#119]
We need to update the config.js comment text in search settings to clarify that the layer name and id come from the layers in the webmap and not from the service directly.  Will need to be updated in config.js 

@LindsayThomas

**Comment by LindsayThomas** [comment]
@lindsayking Added issue #122 for the  configLG.js because work will happen by different PE's

**Comment by lindsayking** [comment]
This is related to #118

**Comment by lindsayking** [comment]
This change has been made in the config.js.
