### ISSUE TITLE
Increase size of map legend

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/live-work-locate#120]
Increase the size of the map legend so it accommodates the symbol styles being built for solution offerings.  

@lindsayking - please review this issue and incorporate it in to next release of LWL.  Assign to dev team after you've reviewed ticket.  May want to also provide dev team a suggested height based on current symbol designs (min # of pixels).

**Comment by lindsayking** [comment]
@ScottOppmann 

According to @HeatherEisan, the size of the new "small" eye drop/pin symbols are 28 pixels wide and 36 pixels high.  Considering this height and appropriate padding, I suggest legend height be set to 68 pixels.

Out of curiosity, have we ever considered making the legend height a configurable item?

**Comment by LindsayThomas** [comment]
Approach for legend should be the same as this issue
https://github.com/Esri/environmental-impact/issues/178

**Comment by LindsayThomas** [comment]
Use the same approach as https://github.com/Esri/environmental-impact/issues/178

**Comment by CTLocalGovTeam** [comment]
@lindsayking @LindsayThomas 
OK. We are following the same approach and shall deliver it in the next release.

**Comment by LindsayThomas** [comment]
LT- Verified on LG config
