### ISSUE TITLE
After sharing, searched location does not persist in search box

### ISSUE THREAD

**Issue by lindsayking** [Esri/live-work-locate#121]
If the app is shared after a search is performed, the shared version of the app displays the default search in the search box, not the location that the user searched.

To repro:
1) Launch the app and select a workflow option from the splash screen
2) Enter a location in the search box on the search panel and indicate a drive or walk time.  Do not use the default address that comes from the <code>LocatorDefaultAddress</code> setting in the app's configuration file.  Remember which address was searched.
3) Share the application.
4) Open the shared version of the app.  Note the search box displays the default search address, not the address that was used in step 2.

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will provide this fix in next release.

**Comment by LindsayThomas** [comment]
LT - Verified on Local Gov Configuration

**Comment by LindsayThomas** [comment]
LT - Verified on Local Gov Configuration
LT- Verified on the State Gov configuration
