### ISSUE TITLE
Reduce and minimize use of global variables in dojo global variable

### ISSUE THREAD

**Issue by lindsayking** [Esri/live-work-locate#124]
Related to Esri/configurable-locator#126.

Code needs to be reviewed and modified to reduce, minimize and limit the number of global variables into the dojo global variable. This work will have the benefit of easier code maintenance over time.  This should be done throughout the codebase.

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will provide this fix in next release.

**Comment by lindsayking** [comment]
@CTLocalGovTeam - please see response by @LindsayThomas at https://github.com/Esri/site-selector/issues/133.

**Comment by CTLocalGovTeam** [comment]
@lindsayking 
OK. We are following the same approach.

**Comment by LindsayThomas** [comment]
Asked @MikeTschudi to validate this fix for the team.

**Comment by LindsayThomas** [comment]
Verified - All uses of “dojo” for hosting global variables have been fixed.
