### ISSUE TITLE
Hard-coded strings should be moved to nls

### ISSUE THREAD

**Issue by lindsayking** [Esri/live-work-locate#125]
There are three places where English is hard-coded:  when the "Show results within x mins drive" is switched between "drive" and "walk", the app will only work in English.
```
this.sliderMessage.innerHTML = this.sliderMessage.innerHTML.replace("walk", "drive");
        :        :        :
this.sliderMessage.innerHTML = this.sliderMessage.innerHTML.replace("drive", "walk");
```

These should be moved into the nls.

**Comment by CTLocalGovTeam** [comment]
@lindsayking We will provide this fix in next release.

**Comment by LindsayThomas** [comment]
LT- Verified that I can see the change has been made in the localizedstring.js (all occurrences) 
Lt - I still need to holistically test this worked

**Comment by LindsayThomas** [comment]
Verified Holistically
