### ISSUE TITLE
Duplicate results in search results

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/live-work-locate#128]
This issue was introduced at the 1.7 code drop 

Duplicate results in search results:
1)	Using http://50.18.115.76/LWLstate or http://50.18.115.76/LWLlocal/ ,
2)	Pick a view (Live, Work or Locate)
3)	Search with a drive time and the default search address
4)	Check the results in the “What’s nearby” panel
5)	Switch to a different view (Live, Work or Locate)
6)	Search with a drive time and the default search address
7)	Check the results in the “What’s nearby” panel.  Notice layers are displayed multiple times.

@lindsayking

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas We have resolved this issue and shall deliver it in the next release.

**Comment by LindsayThomas** [comment]
SG Verified
LG Verified
