### ISSUE TITLE
graphic not displaying correctly in many scenarios

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/live-work-locate#129]
@CTLocalGovTeam Something was introduced in the 1.7 drop that is causing issues with the display of graphics on the map

Repo Step - I
1)  For http://50.18.115.76/LWLlocal, 
2) Search using default address and a 10min drive time. 
3) Expand Hospitals > Click on "Edward Hospital and Medical Center"
4) Popup displays but points and other graphics are not displayed

Repo Steps - II
1) For http://50.18.115.76/LWLstate, 
2) search using an address and at least a 20min drive time.
3) Expand the search results and click on a point feature in the results
4)Note the map shifts/zooms slightly and the popup displays, but the basemap does not completely resolve and features do not display on the map.  The user has to zoom in/out on the map for the features and drive time polygon to display.

@NikkiGolding @lindsayking

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas We have resolved this issue and shall deliver it in the next release.

**Comment by LindsayThomas** [comment]
SG\LG verified
