### ISSUE TITLE
Legend Behavior- Make Static

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/live-work-locate#130]
What is the level of effort to make the legend static?

We are seeing inconsistent behavior across browsers and rather than trying to fix the inconsistent behavior, we;d like to determine if we can easily change the legend to be static.

 we have done this in EIA and would like to consider it for Live, Work, Locate.

**Comment by CTLocalGovTeam** [comment]
@lindsayking Legend panel will be displayed for all the layers on map load. In this app, for server configuration, feature layers are added in selection mode and features are visible only on selecting an address. So the legend will be displayed even if features from these layers are not visible on map. This is because the layers are turned on, but no features are selected to display yet. Please confirm.

**Comment by CTLocalGovTeam** [comment]
@NikkiGolding The issue was incorrectly addressed to Lindsay King. Could you please confirm on this?

**Comment by lindsayking** [comment]
@CTLocalGovTeam Please implement the legend the same way as was done for Environmental Impact.

Also, can you explain what you mean by a 'server configuration' in your comment above?  We have moved to a webmap-only approach and should no longer have server configurations.

**Comment by CTLocalGovTeam** [comment]
@lindsayking We are implementing legend the same way as it has been implemented for EI. 

Operational layers can be configured using `OperationalLayers` for implementing the 'server' configuration in both the apps. However EI supports both 'server' and 'webmap' configuration.  

One can always disable server configuration by providing a webmap in `WebMapId` and/or removing the configuration settings `OperationalLayers`.

Our question from previous comment is invalid as we do not need to support server configuration for LWL.

**Comment by NikkiGolding** [comment]
@CTLocalGovTeam Per our conversation this morning, please do not modify the overall code base to remove the server configuration. This code should remain in the code base.

**Comment by LindsayThomas** [comment]
-Legend is now static
-looking at op now
