### ISSUE TITLE
ENH-000085686  Change the  QueryLayerId for the LiveWorkLocate template to reference the map layer index instead of the service layer index. This will allow the template to search for locations from multiple services.

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/live-work-locate#131]
<div><div>
<span><b>Salesforce ID:</b> ENH-000085686</span><br/>
<span><b>Salesforce Submitter:</b> Kara Manseau</span><br/>
<span><b>Salesforce Submit Date:</b> 2/26/2015 6:41 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Process</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> 0</span><br/>
<span><b>Work Around:</b> If a user is trying to use a service that is owned by someone else wihtin their application, they are not able to do this. The reason for this is that all layers need to be published as a single service and if they do not have access to the source data, it prevents them from using the data.</span><br/>
<span><b>Product:</b> ArcGIS for State Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for State Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> No Version Found</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
Once #118 is closed and we have a release date for Version 2 to go public. Then we need to close this issue and go into the triage application to update this.

**Comment by NikkiGolding** [comment]
@LindsayThomas  I updated the  info in Triage.
