### ISSUE TITLE
Must click the expand results button twice to expand results

### ISSUE THREAD

**Issue by lindsayking** [Esri/live-work-locate#137]
There is a specific scenario in which the user must click the "expand results" button twice in order to expand results in the "what's nearby?" panel.

Steps to repro:
1) Search with an address and a drive or walk time
2) Once the "what's nearby?" panel has been populated with search results, click the expand results button to expand all results.
3) Change the drive or walk time on the time slider to execute a new search (keep location the same).
4) Note that once the second drive/walk time has executed and the "what's nearby?" is populated with new search results, the search results are collapsed, button the 'expand/collapse' button is set to "collapse results".  You must click "collapse results" (with no effect), which then changes to "expand results" and then click "expand results" in order to expand the results.

**Comment by LindsayThomas** [comment]
@lindsayking did this exist in the current release?

**Comment by lindsayking** [comment]
@LindsayThomas   Yes, this issue is present in the current release.  It is not a new issue.

**Comment by LindsayThomas** [comment]
App is moving to Mature Support
