### ISSUE TITLE
Search address inconsistently persists between apps

### ISSUE THREAD

**Issue by lindsayking** [Esri/live-work-locate#138]
Reported by @jessnoo 

If a non-default search address is used, that address inconsistently persists between apps (e.g. live, work or locate apps) depending on how the user switches between the apps.

Scenario 1, switch using the Exit button:
1) Search using a non-default search address
2) Once search completes, use the exit button to switch from the current app to one of the other apps (e.g. switch from "live" to "locate)
3) Note that in the second app, the non-default address has persisted.

Scenario 2, switch using the header toggle buttons:
1) Search using a non-default search address
2) Once the search completes, use one of the three app-specific buttons on the left side of the header to switch to one of the other apps (e.g. switch from "live" to "locate)
3) Note that in the second app, the non-default address is forgotten and the default search address displays.

The persistence of the non-default search address should be consistent regardless of how the user switches between apps.

**Comment by lindsayking** [comment]
This is not a new issue.  It exists in the previous releases of Live Work Locate.

**Comment by LindsayThomas** [comment]
App is moving to Mature Support
