### ISSUE TITLE
LWL proxy update

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/live-work-locate#142]
@lindsayking I think we have extraneous service ref's in the proxy. Let's update before we tag it . 

- [ ] State
- [ ] Local

**Comment by LindsayThomas** [comment]
http://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/  = ? - LT no dependency 
http://services6.arcgis.com/Pu6Fai10JE2L2xUd/arcgis/ = New try it org - LT uses 
http://services.arcgis.com/b6gLrKHqgkQb393u/arcgis/" = LG dev ORG - LT no dependency 
http://services.arcgis.com/doC3DvW5p9jGtDST/arcgis/ = ? -
http://arcgis-gov-1244222493.us-west-2.elb.amazonaws.com/arcgis/rest/services = State TIL -  LT no dependency 

@lindsayking can you look at this ?

**Comment by lindsayking** [comment]
@LindsayThomas 

http://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/ = ? - LT no dependency, LK no State dependency 
http://services6.arcgis.com/Pu6Fai10JE2L2xUd/arcgis/ = New try it org - LT uses, LK uses
http://services.arcgis.com/b6gLrKHqgkQb393u/arcgis/" = LG dev ORG - LT no dependency, LK no dependency 
http://services.arcgis.com/doC3DvW5p9jGtDST/arcgis/ = Former state TIL webmaps use this, new TIL webmaps do not
http://arcgis-gov-1244222493.us-west-2.elb.amazonaws.com/arcgis/rest/services = State TIL - LT no dependency, no State dependency for LWL TIL

**Comment by LindsayThomas** [comment]
@lindsayking can we go ahead and remove?

**Comment by lindsayking** [comment]
@lindsaythomas Yes.

**Comment by lindsayking** [comment]
@LindsayThomas  Extraneous serverUrls have been removed.
