### ISSUE TITLE
Point config.js and proxy to try it live webmap id and services

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/live-work-locate#143]
Point config.js and proxy to try it live webmap id and services
- [x] config.js updated to reflect the tryitlive version of the application
- [x] proxy file references to dev server removed

**Comment by lindsayking** [comment]
@LindsayThomas 

* config.js - no changes needed.  The only difference between the master branch and the try it live version is the splash screen images, which are intentionally different.
* configLG.js - no changes needed.  The master branch matches the try it live version.
* proxy.config - no changes needed.
