### ISSUE TITLE
Walk time results- Zoom extent

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/live-work-locate#90]
When using a walk time result, if you click on a point result in the panel. The map extent changes too drastically. The application zooms way out.

http://203.199.47.146/LiveWorkLocate_v1.6/#?app=LOCATE

Repro Steps
-Use the default address for the app
-Set the walk time to 30 minutes
-Expand research Parks 
-Click the first result
-Observe the map extent is adjusted to a much bigger extent.

**Comment by lindsayking** [comment]
We will adjust this in the config.js.
